### ISSUE TITLE
pretrain weights and how many iterations for  pre-training

### ISSUE THREAD

**Issue by ray8828** [jimmy15923/unsup_point_coseg#15]
Hi, could you provide how many epoches for modelnet40 cls pre training? the best is to release the pre-trained weight to reproduce the results, thanks

**Comment by jimmy15923** [comment]
Hi @ray8828!
Please see here to find the pre-trained weights and the running log
https://github.com/jimmy15923/unsup_point_coseg/blob/main/README.md#pre-training
