### ISSUE TITLE
Unable to generate S3D and ScanObjectNN datasets

### ISSUE THREAD

**Issue by yyyyy1231** [jimmy15923/unsup_point_coseg#3]
Thanks for the great work.

I want to know how to use data_ preprocess/parse_ data.py to generate S3D and ScanObjectNN datasets.
The code will fail and display "Unable to open object (object 'coords' doesn't exist)".

**Comment by jimmy15923** [comment]
Hi!
Thanks for being interesting in this project. Please follow this [repo](https://github.com/pqhieu/jsis3d/issues/1) for downloading the S3DIS dataset.

**Comment by yyyyy1231** [comment]
I'm not sure if the link to your S3DIS dataset is correct.
And this [repo](https://github.com/pqhieu/jsis3d/) is suit for parse_ data.py.
