### ISSUE TITLE
Cannot do the data preprecessing 

### ISSUE THREAD

**Issue by tengyoyo** [jimmy15923/unsup_point_coseg#5]
I try to run `python data_preprocess/parse_data.py `
But I keep getting the same error 
```
Traceback (most recent call last):

  File ~/work/unsup/data_preprocess/parse_data.py:28 in <module>
    raw_points = np.array(file['coords'])

  File h5py/_objects.pyx:54 in h5py._objects.with_phil.wrapper

  File h5py/_objects.pyx:55 in h5py._objects.with_phil.wrapper

  File ~/anaconda3/envs/unsup0317/lib/python3.8/site-packages/h5py/_hl/group.py:305 in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)

  File h5py/_objects.pyx:54 in h5py._objects.with_phil.wrapper

  File h5py/_objects.pyx:55 in h5py._objects.with_phil.wrapper

  File h5py/h5o.pyx:190 in h5py.h5o.open

KeyError: "Unable to open object (object 'coords' doesn't exist)"

```

The dataset is form the link you mentioned  [https://shapenet.cs.stanford.edu/media/indoor3d_sem_seg_hdf5_data.zip](url)
I downloaded a few times to make sure the file wasn't corrupted, but it didn't work.
I also changed the directory path in parse_data.py at first.
Maybe I should download scanobjectnn dataset? 
Can't see the dependency on it. 

Thank you!

**Comment by jimmy15923** [comment]
Hi @tengyoyo !

Please refer to [this repo](https://github.com/pqhieu/jsis3d/blob/master/scripts/prepare_h5.py) to process the data.
