### ISSUE TITLE
Pre-trained weights.

### ISSUE THREAD

**Issue by yyyyy1231** [jimmy15923/unsup_point_coseg#7]
Without the use of pre-trained weights, the mIoU result on the s3dis dataset is only 0.3, which is lower than the 0.463 in the text. I hope you can provide a pre-trained model or a final model.

**Comment by jimmy15923** [comment]
Hi!
Our method requires the pre-trained model to guide the SampleNet. It can be obtained through the [pretrain.py](https://github.com/jimmy15923/unsup_point_coseg/blob/main/pretrain.py), which is simply a classification task.
