### ISSUE TITLE
the problem of importing packages

### ISSUE THREAD

**Issue by BIAO-ac** [jimmy15923/unsup_point_coseg#8]
the line 6 in the file \unsup_point_coseg-main\models\src\soft_projection.py .
I can't find the package named pointnet2. Meanwhile, I have searched the pointnet2 codes in github, but I can't find a version which fits the package.Could you please tell me where the pointnet2 package is?Thank you very much.

**Comment by jimmy15923** [comment]
Hi @BIAO-ac ,

Please refer to the installation of [SampleNet](https://github.com/itailang/SampleNet/tree/master/registration#installation). I highly recommend using docker to run our code.
